name: Java CI Demo in GitHub Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Update Changelog inside README.md
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_TYPE=$(git log -1 --pretty=%s | cut -d' ' -f1 | tr -d ':')
          COMMIT_DESC=$(git log -1 --pretty=%s | cut -d' ' -f2-)
          sed -i "10i| **$COMMIT_HASH** | $COMMIT_TYPE | $COMMIT_DESC |" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update Changelog"
          git push